import { MccCategory, SpecialSector, StandardDeductionRule } from '../types';

/**
 * Official NPCI Standard Deduction Rules for UPI P2M Transactions
 * Effective Date: October 15, 2026
 * Source: NPCI Circular / FAQs on Merchant Discount Rate (MDR) on Select UPI (P2M) Transactions
 */
export const NPCI_STANDARD_DEDUCTION_RULES: StandardDeductionRule[] = [
  {
    id: 'rule_standard_p2m',
    title: 'Standard UPI P2M Deduction Rule',
    subtitle: 'General Retail, Dining, E-commerce, Supermarkets & Services',
    category: 'General Merchant P2M',
    thresholdCondition: 'Applies only to transactions > ₹2,000',
    rateType: 'percentage',
    rateDisplay: '0.40% MDR',
    baseRateValue: 0.40,
    capDisplay: 'Max ₹300 Cap (for ₹75,000+)',
    capAmount: 300,
    exemptionRule: '100% Free (0% MDR) on all transactions ≤ ₹2,000',
    effectiveDate: 'October 15, 2026',
    eligibleMerchants: 'All registered business merchants with monthly UPI turnover exceeding ₹1,00,000 (standard P2M category).',
    exampleCalculation: 'On ₹10,000 bill: MDR is ₹40.00 (0.4%) + ₹7.20 GST = ₹47.20 deduction. On ₹1,00,000 bill: MDR is ₹300 (capped) + ₹54 GST = ₹354 deduction.',
  },
  {
    id: 'rule_sector_flat5',
    title: 'Specialized Essential Sectors Rule',
    subtitle: 'Railways, Telecom, Insurance, Fuel, Utilities, Education & Agriculture',
    category: 'Essential Sector Slabs',
    thresholdCondition: 'Applies only to transactions > ₹2,000',
    rateType: 'flat',
    rateDisplay: 'Flat ₹5.00 per txn',
    baseRateValue: 5.0,
    capDisplay: 'Flat ₹5 Fixed (No percentage)',
    exemptionRule: '100% Free (0% MDR) on all transactions ≤ ₹2,000',
    effectiveDate: 'October 15, 2026',
    eligibleMerchants: 'Railways (IRCTC), Telecom operators, Insurance providers, Petrol pumps/CNG, Power/Water utilities, Schools/Colleges, Agri inputs.',
    exampleCalculation: 'On ₹2,500 electricity bill or ₹50,000 college fee: Flat ₹5.00 MDR + ₹0.90 GST (18%) = ₹5.90 total deduction regardless of ticket size!',
  },
  {
    id: 'rule_capital_markets',
    title: 'Capital Markets & Financial Securities Rule',
    subtitle: 'Mutual Funds, Stockbrokers, Securities Dealers & Asset Management',
    category: 'Financial Market Slabs',
    thresholdCondition: 'Applies only to transactions > ₹2,000',
    rateType: 'percentage',
    rateDisplay: '0.02% MDR',
    baseRateValue: 0.02,
    capDisplay: 'Max ₹300 Cap per transaction',
    capAmount: 300,
    exemptionRule: '100% Free (0% MDR) on all transactions ≤ ₹2,000',
    effectiveDate: 'October 15, 2026',
    eligibleMerchants: 'SEBI-registered stockbrokers, Mutual Fund AMCs, Depository participants, securities exchanges.',
    exampleCalculation: 'On ₹50,000 SIP / stock purchase: MDR is ₹10.00 (0.02%) + ₹1.80 GST = ₹11.80 deduction.',
  },
  {
    id: 'rule_small_merchant_p2pm',
    title: 'Small Merchant / P2PM Zero-MDR Exemption',
    subtitle: 'Street Vendors, Tea Stalls, Local Kiranas & Micro Retailers',
    category: 'Micro Merchant Protection',
    thresholdCondition: 'Monthly UPI collections up to ₹1,00,000',
    rateType: 'exempt',
    rateDisplay: '0.00% (100% Free)',
    baseRateValue: 0.0,
    capDisplay: 'No Charges Levied',
    exemptionRule: 'Full waiver under NPCI P2PM guideline for personal bank account QR codes',
    effectiveDate: 'Active (Protected by RBI / NPCI)',
    eligibleMerchants: 'Merchants receiving up to ₹1 Lakh/month. If volume exceeds ₹1 Lakh for 3 consecutive months, transitions to standard P2M.',
    exampleCalculation: 'A tea stall or roadside fruit seller doing ₹70,000/month pays exactly ₹0.00 in MDR fees.',
  },
  {
    id: 'rule_rupay_credit',
    title: 'RuPay Credit Card on UPI Rule',
    subtitle: 'Credit cards linked to UPI apps (Google Pay, PhonePe, Paytm, BHIM)',
    category: 'Credit Card on UPI',
    thresholdCondition: 'Transactions > ₹2,000 subject to credit MDR',
    rateType: 'percentage',
    rateDisplay: '~1.99% MDR',
    baseRateValue: 1.99,
    exemptionRule: '100% Free (0% MDR) on all transactions ≤ ₹2,000',
    effectiveDate: 'Active NPCI Circular',
    eligibleMerchants: 'Merchants accepting RuPay Credit Cards over merchant QR standees or POS terminals.',
    exampleCalculation: 'On ₹3,000 bill: MDR is ₹59.70 (1.99%) + ₹10.75 GST = ₹70.45 deduction.',
  },
  {
    id: 'rule_ppi_wallets',
    title: 'Prepaid Wallets (PPI) on UPI Rule',
    subtitle: 'Paytm Wallet, PhonePe Wallet, Amazon Pay Wallet',
    category: 'Prepaid Wallet Instruments',
    thresholdCondition: 'Transactions > ₹2,000 subject to interchange',
    rateType: 'percentage',
    rateDisplay: '0.50% - 1.10% MDR',
    baseRateValue: 1.10,
    capDisplay: 'Max ₹15 Cap for Fuel',
    exemptionRule: '100% Free (0% MDR) on all transactions ≤ ₹2,000',
    effectiveDate: 'Active NPCI Circular',
    eligibleMerchants: 'Merchants accepting wallet balances over interoperable UPI QR codes.',
    exampleCalculation: 'On ₹2,500 grocery bill: MDR is ₹22.50 (0.90%) + ₹4.05 GST = ₹26.55 deduction.',
  },
];

/**
 * The 7 Specialized Essential Sectors entitled to Flat ₹5 MDR above ₹2,000
 */
export const SPECIALIZED_SECTORS_FLAT5: SpecialSector[] = [
  {
    id: 'railways',
    name: 'Railways & Train Ticketing',
    shortName: 'Railways',
    iconName: 'Train',
    examples: 'IRCTC online booking, Railway station ticket counters, UTS app, PRS reservations',
    mccCodes: 'MCC 4112, 4011',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
  {
    id: 'telecom',
    name: 'Telecommunications & Broadband',
    shortName: 'Telecom',
    iconName: 'Radio',
    examples: 'Airtel, Jio, Vi mobile postpaid/prepaid recharges, fiber broadband, DTH connections',
    mccCodes: 'MCC 4814, 4899',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
  {
    id: 'insurance',
    name: 'Insurance Premiums',
    shortName: 'Insurance',
    iconName: 'Shield',
    examples: 'LIC, HDFC Life, ICICI Lombard, health insurance, motor vehicle insurance policies',
    mccCodes: 'MCC 6300, 5960',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
  {
    id: 'fuel',
    name: 'Fuel & Gas Dispensing Stations',
    shortName: 'Fuel Stations',
    iconName: 'Fuel',
    examples: 'Petrol pumps, Indian Oil, Bharat Petroleum, HPCL, Shell, CNG fuel outlets',
    mccCodes: 'MCC 5541, 5542, 5983',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
  {
    id: 'utilities',
    name: 'Government Utilities & Municipal Taxes',
    shortName: 'Govt Utilities',
    iconName: 'Zap',
    examples: 'Electricity bills (State discoms), Water supply boards, Piped Natural Gas, Property tax',
    mccCodes: 'MCC 4900, 9399',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
  {
    id: 'education',
    name: 'Educational Institutions & Universities',
    shortName: 'Education',
    iconName: 'GraduationCap',
    examples: 'Schools, colleges, universities, higher education tuition fees, entrance exams',
    mccCodes: 'MCC 8211, 8220, 8299',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
  {
    id: 'agriculture',
    name: 'Agriculture Inputs & Farming Supplies',
    shortName: 'Agriculture',
    iconName: 'Wheat',
    examples: 'Fertilizers, hybrid seeds, agricultural machinery, pesticides, Kisan credit outlets',
    mccCodes: 'MCC 0780, 5193, 5261',
    feeStructure: 'Flat ₹5.00 (+ 18% GST = ₹5.90) for transactions > ₹2,000. 100% Free ≤ ₹2,000.',
  },
];

/**
 * NPCI MCC Categories for PPI Wallets on UPI
 */
export const NPCI_MCC_CATEGORIES: MccCategory[] = [
  {
    id: 'general_retail',
    name: 'General Retail, Apparel & Dining',
    code: 'MCC 5311, 5691, 5812, etc.',
    description: 'Clothing, restaurants, electronics, department stores & e-commerce',
    interchangeRate: 1.10,
    badge: '1.10% Interchange',
  },
  {
    id: 'supermarket',
    name: 'Supermarket & Grocery Stores',
    code: 'MCC 5411, 5422, 5499',
    description: 'Kirana stores, supermarkets, meat markets, dairy & grocery outlets',
    interchangeRate: 0.90,
    badge: '0.90% Interchange',
  },
  {
    id: 'utilities_telecom',
    name: 'Utilities, Telecom, Education & Agri',
    code: 'MCC 4814, 4899, 4900, 8220',
    description: 'Electricity, water, broadband, mobile recharges, school/college fees',
    interchangeRate: 0.70,
    badge: '0.70% Interchange',
  },
  {
    id: 'fuel',
    name: 'Fuel Stations & Gas Outlets',
    code: 'MCC 5541, 5542, 5983',
    description: 'Petrol pumps, diesel, CNG and fuel dispensing stations (Capped at ₹15)',
    interchangeRate: 0.50,
    capAmount: 15,
    badge: '0.50% (Max ₹15 Cap)',
  },
  {
    id: 'govt_insurance_railway',
    name: 'Govt, Insurance, Mutual Funds & IRCTC',
    code: 'MCC 9399, 6300, 6211, 4112',
    description: 'Income tax, insurance premiums, train tickets, municipal payments',
    interchangeRate: 1.00,
    badge: '1.00% Interchange',
  },
];

export const PAYMENT_MODES_INFO = [
  {
    id: 'upi_p2m_standard',
    title: 'Standard UPI P2M (0.40%)',
    subtitle: 'General retail & merchant payments > ₹2,000',
    tag: '0.40% (₹300 Cap)',
    badgeColor: 'bg-blue-500/10 text-blue-600 border-blue-500/20 dark:text-blue-400',
    description: 'Standard Person-to-Merchant rate for transactions exceeding ₹2,000. Capped at ₹300 for ₹75,000+. Transactions ≤ ₹2,000 are 100% Free.',
  },
  {
    id: 'upi_p2m_flat5',
    title: 'Essential Sectors (Flat ₹5)',
    subtitle: 'Railways, Fuel, Telecom, Insurance, Utilities, Education',
    tag: 'Flat ₹5 / Txn',
    badgeColor: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20 dark:text-emerald-400',
    description: 'Specialized vital sectors have a flat fee of ₹5 per transaction for payments above ₹2,000 (+ 18% GST). Transactions ≤ ₹2,000 are 100% Free.',
  },
  {
    id: 'upi_p2m_capital',
    title: 'Capital Markets (0.02%)',
    subtitle: 'Mutual Funds, Stockbrokers, Securities Dealers',
    tag: '0.02% (₹300 Cap)',
    badgeColor: 'bg-teal-500/10 text-teal-600 border-teal-500/20 dark:text-teal-400',
    description: 'Transactions for mutual funds, stock trading, and securities. 0.02% MDR capped at ₹300 per transaction. Free ≤ ₹2,000.',
  },
  {
    id: 'upi_p2pm_small',
    title: 'Small Merchant / P2PM (0%)',
    subtitle: 'Street vendors, tea stalls, retail < ₹1 Lakh/month',
    tag: '100% Free (0%)',
    badgeColor: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20 dark:text-emerald-400',
    description: 'Micro merchants receiving up to ₹1,00,000/month into personal accounts have zero MDR charges. If volume > ₹1L for 3 months, transitions to standard P2M.',
  },
  {
    id: 'rupay_credit',
    title: 'RuPay Credit Card on UPI',
    subtitle: 'Credit Card linked to UPI apps',
    tag: '0% up to ₹2k | ~1.99% above',
    badgeColor: 'bg-indigo-500/10 text-indigo-600 border-indigo-500/20 dark:text-indigo-400',
    description: 'Transactions ≤ ₹2,000 have 0% MDR. Above ₹2,000 incurs standard credit MDR (typically 1.99% + 18% GST).',
  },
  {
    id: 'ppi_wallet',
    title: 'PPI Wallets on UPI',
    subtitle: 'Paytm, PhonePe, Amazon Pay Wallet balance',
    tag: 'Tiered 0.5% - 1.10%',
    badgeColor: 'bg-amber-500/10 text-amber-600 border-amber-500/20 dark:text-amber-400',
    description: 'Transactions ≤ ₹2,000 are 100% Free. Above ₹2,000 attracts 0.50% - 1.10% interchange based on MCC + 18% GST.',
  },
];
